parameters:
    pim_catalog.entity.product_value.class: Acme\Bundle\AppBundle\Model\ProductValue
    pimee_workflow.entity.published_product_value.class: Acme\Bundle\AppBundle\Model\PublishedProductValue
