Pim\Bundle\ExtendedAttributeTypeBundle\Model\PublishedProductRange:
    type: entity
    table: pimee_workflow_published_range
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        min:
            type: string
            nullable: true
        max:
            type: string
            nullable: true
    oneToOne:
        value:
            targetEntity: PimEnterprise\Component\Workflow\Model\PublishedProductValueInterface
            mappedBy: range
            joinColumns:
                value_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
