Acme\Bundle\AppEEBundle\Model\PublishedProductValue:
    type: embeddedDocument
    fields:
        range:
            embedded: true
            type: one
            targetEntity: Pim\Bundle\ExtendedAttributeTypeBundle\Model\PublishedProductRange
