parameters:
    pim_extended_attribute_type.array_converter.flat_to_standard.range_converter.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\FlatToStandard\RangeConverter
    pim_extended_attribute_type.array_converter.standard_to_flat.range_converter.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\StandardToFlat\RangeConverter

services:
    pim_extended_attribute_type.array_converter.flat_to_standard.range_converter:
        class: '%pim_extended_attribute_type.array_converter.flat_to_standard.range_converter.class%'
        tags:
            - { name: 'pim_connector.array_converter.flat_to_standard.product.value_converter' }

    pim_extended_attribute_type.array_converter.standard_to_flat.range_converter:
        class: '%pim_extended_attribute_type.array_converter.standard_to_flat.range_converter.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }
