parameters:
    pim_extended_attribute_type.comparator.product_range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Comparator\Attribute\RangeComparator

services:
    pim_extended_attribute_type.comparator.product_range:
        class: '%pim_extended_attribute_type.comparator.product_range.class%'
        tags:
            - { name: pim_catalog.attribute.comparator }
