parameters:
    pim_extended_attribute_type.completeness.checker.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Completeness\Checker\RangeCompleteChecker

services:
    pim_extended_attribute_type.completeness.checker.range:
        class: '%pim_extended_attribute_type.completeness.checker.range.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }
