parameters:
    pim_extended_attribute_type.structured.normalizer.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Normalizer\Structured\RangeNormalizer
    pim_extended_attribute_type.structured.flat.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Normalizer\Flat\RangeNormalizer

services:
    pim_extended_attribute_type.structured.normalizer.range:
        class: '%pim_extended_attribute_type.structured.normalizer.range.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_extended_attribute_type.flat.normalizer.range:
        class: '%pim_extended_attribute_type.flat.normalizer.range.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
            - { name: pim_versioning.serializer.normalizer, priority: 90 }
