parameters:
    pim_extended_attribute_type.structured.normalizer.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Normalizer\Structured\RangeNormalizer

services:
    pim_extended_attribute_type.structured.normalizer.range:
        class: '%pim_extended_attribute_type.structured.normalizer.range.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
