parameters:
    pim_extended_attribute_type.normalizer.structured.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Normalizer\Structured\RangeNormalizer
    pim_extended_attribute_type.normalizer.flat.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Normalizer\Flat\RangeNormalizer

services:
    pim_extended_attribute_type.normalizer.structured.range:
        class: '%pim_extended_attribute_type.normalizer.structured.range.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_extended_attribute_type.normalizer.flat.range:
        class: '%pim_extended_attribute_type.normalizer.flat.range.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
            - { name: pim_versioning.serializer.normalizer, priority: 90 }
