parameters:
    pim_extended_attribute_type.provider.field.range.class: Pim\Bundle\ExtendedAttributeTypeBundle\Provider\RangeFieldProvider
    pim_extended_attribute_type.provider.empty_value.range.class: Training\Bundle\AttributeTypeBundle\Provider\EmptyValue\RangeEmptyValueProvider

services:
    pim_extended_attribute_type.provider.field.range:
        class: '%pim_extended_attribute_type.provider.field.range.class%'
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }

    training_attribute_type.provider.empty_value.range:
        class:
        tags:
            - { name: pim_enrich.provider.empty_value, priority: 90 }
