config:
    paths:
        # Datagrid filter
        oro/datafilter/range-filter: pimextendedattributetype/js/datafilter/filter/range-filter

        # Form
        pim-extended-attribute-type/range-field: pimextendedattributetype/js/product/field/range-field

        # Template
        pim-extended-attribute-type/templates/product/field/range: pimextendedattributetype/templates/product/field/range.html
