parameters:
    pim_extended_attribute_type.updater.copier.range_value.class: Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Copier\RangeAttributeCopier
    pim_extended_attribute_type.updater.setter.range_value.class: Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Setter\RangeAttributeSetter

services:
    pim_extended_attribute_type.updater.copier.range_value:
        class: '%pim_extended_attribute_type.updater.copier.range_value.class%'
        parent: pim_catalog.updater.copier.abstract
        tags:
            - { name: 'pim_catalog.updater.copier' }

    pim_extended_attribute_type.updater.setter.range_value:
        class: '%pim_extended_attribute_type.updater.setter.range_value.class%'
        parent: pim_catalog.updater.setter.abstract
        tags:
            - { name: 'pim_catalog.updater.setter' }
