Acme\Bundle\AppBundle\Model\ProductValue:
    type: entity
    table: pim_catalog_product_value
    changeTrackingPolicy: DEFERRED_EXPLICIT
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
    oneToOne:
        range:
            targetEntity: Pim\Bundle\ExtendedAttributeTypeBundle\Model\ProductRange
            cascade:
                - remove
                - persist
                - refresh
                - detach
            inversedBy: value
            joinColumns:
                range_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
