Acme\Bundle\AppBundle\Model\ProductValue:
    type: embeddedDocument
    fields:
        range:
            embedded: true
            type: one
            targetEntity: Pim\Bundle\ExtendedAttributeTypeBundle\Model\ProductRange
