Pim\Bundle\ExtendedAttributeTypeBundle\Model\PublishedProductRange:
    type: embeddedDocument
    fields:
        id:
            id: true
        min:
            type: float
        max:
            type: float
