Pim\Bundle\ExtendedAttributeTypeBundle\Model\Range:
    type: embeddedDocument
    fields:
        id:
            id: true
        fromData:
            type: float
        toData:
            type: float
